import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/main/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <main>
                <body>
                    <Navbar />
                    {children}
                </body>
            </main>
        </html>
    );
}
